language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-frontend hoavy021/udagram-frontend:v2
  - docker tag udagram-api-feed hoavy021/udagram-api-feed:v2
  - docker tag udagram-api-user hoavy021/udagram-api-user:v2
  - docker tag reverseproxy hoavy021/reverseproxy:v2

after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoavy021/udagram-api-feed:v2
  - docker push hoavy021/udagram-api-user:v2
  - docker push hoavy021/udagram-frontend:v2
  - docker push hoavy021/reverseproxy:v2